/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Enuns;

/**
 *
 * @author Fagner
 */
public enum TipoControllerMouse {
    
    CAIXA_SELECAO_COZINHEIRO , CAIXA_SELECAO_MAE , 
    INICIAR_THREAD_MAE, INICIAR_THREAD_COZINHEIRO, 
    VELOCIDADE_MAE, VELOCIDADE_COZINHEIRO, 
    REINICIAR, AJUDA, 
    ESTADO_NOVA_COZINHEIRO, ESTADO_INICIADA_COZINHEIRO, ESTADO_EXECUCAO_COZINHEIRO, ESTADO_DORMINDO_COZINHEIRO, 
    ESTADO_ESPERANDO_COZINHEIRO, ESTADO_TERMINADA_COZINHEIRO,
    ESTADO_INICIADA_MAE, ESTADO_NOVA_MAE, ESTADO_EXECUCAO_MAE, ESTADO_DORMINDO_MAE, 
    ESTADO_ESPERANDO_MAE, ESTADO_TERMINADA_MAE,
    BOTAO_AJUDA_UM, BOTAO_AJUDA_DOIS, BOTAO_AJUDA_TRES, BOTAO_AJUDA_QUATRO, BOTAO_AJUDA_CINCO;  
    
}
